### ISSUE TITLE
Preferred citation

### ISSUE THREAD

**Issue by kevinyamauchi** [haesleinhuepf/napari-process-points-and-surfaces#62]
Hello everyone! I was wondering if there is a preferred way to cite this awesome library. 

Thanks,
Kevin

**Comment by haesleinhuepf** [comment]
Hi Kevin,

we have a DOI, just the button is missing in the readme yet:

[![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.6617976.svg)](https://doi.org/10.5281/zenodo.6617976)

Best,
Robert

**Comment by kevinyamauchi** [comment]
Awesome. Thanks! I've made a PR adding it to the readme :) https://github.com/haesleinhuepf/napari-process-points-and-surfaces/pull/63
