### ISSUE TITLE
Changing focus from Shapes back to Image

### ISSUE THREAD

**Issue by JosephBendahan** [haesleinhuepf/napari-process-points-and-surfaces#69]
Hi,
I wrote a piece of code that adds a circle at the position of the mouse when  I press 1, which works fine.
Then, I go to another location and press 1 and nothing happens; the cursors changes from pointer to crosshair.
When I manually change the focus to Image, then it works again.
My guess is that is trying to draw another circle while in the Shapes first circle, which cannot do.

How do I change programmatically the focus back to Image?
Thank you.

**Comment by haesleinhuepf** [comment]
Hi @JosephBendahan ,

would you mind asking this question on image.sc? Post your code there so others can have a look. Add the tag "napari" and I'm sure people will help.

Best,
Robert
