### ISSUE TITLE
Decimation API changed

### ISSUE THREAD

**Issue by jo-mueller** [haesleinhuepf/napari-process-points-and-surfaces#90]
Hi @haesleinhuepf ,

some of the more recent versions of vedo introduced some more API changes. In particular, the `method` keyword of the `decimate` function doesn't exist anymore - there are now separate functions `decimate`, `decimate_pro` and `decimate_binned`. Will send a PR to fix this and pinpoint vedo to a newer version.

Sidenote: This will probably make issue #87 more pressing. There are likely more problems with newer APIs (see also PR #88)

**Comment by haesleinhuepf** [comment]
Hi @jo-mueller ,

how about pinning the vedo version? They are breaking the API all the time causing efforts on our side.

Or are there any new features in vedo, that we need here?

Thanks!

Best,
Robert

**Comment by jo-mueller** [comment]
Hi @haesleinhuepf ,

> how about pinning the vedo version?

This would probably work. I would have to go through the past few version though to see which change was introduced when. Would you be ok in fixing the last two changes (this issue and #87 ) and then pinning it? I am now a vedo maintainer so I can hopefully avert these kinds of breaking changes in the future :)

**Comment by haesleinhuepf** [comment]
> Would you be ok in fixing the last two changes (this issue and #87 ) and then pinning it? I am now a vedo maintainer so I can hopefully avert these kinds of breaking changes in the future :)

Awesome! Do you want to take over this repository too? It would be your decision then.

**Comment by jo-mueller** [comment]
I wouldn't mind :) Would you then leave it here or would you prefer moving the repository elsewhere?
