### ISSUE TITLE
Maintenance

### ISSUE THREAD

**Issue by jo-mueller** [haesleinhuepf/napari-process-points-and-surfaces#92]
Hi @haesleinhuepf ,

following up our brief conversation the other day I'm just creating a new issue here to discuss how to go forward with the maintenance here. Currently, the plugin is broken in multiple places (#90, #87) due to changes in the vedo API (or vtk, I don't now). There may be a few more I didn't run into yet. There are a few PRs fixing stuff ( #88 , #91) but I understand that you may not have enough time to look at them in depth.

So...what would be your ideal scenario of how to maintain it? I am happy to keep up maintenance for now, but without code review that would boil down to me merging PRs autonomously. 

Happy to hear your thoughts.

**Comment by haesleinhuepf** [comment]
> Currently, the plugin is broken in multiple places (#90, #87) due to changes in the vedo API

Are you sure? When following the instructions here, everything seems to work fine for me:

https://github.com/haesleinhuepf/napari-process-points-and-surfaces?tab=readme-ov-file#installation

**Comment by jo-mueller** [comment]
@haesleinhuepf Should I put that in the `setup.cfg`? Makes it easier to install the plugin from other places such as the plugins menu or devbio-napari.
